version: '3.3'

services:
  web_server_1:
    image: hypriot/rpi-whoami
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - frontend

  web_server_2:
    image: hypriot/rpi-whoami
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - frontend

  web_server_3:
    image: hypriot/rpi-whoami
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - frontend

  web_server_4:
    image: hypriot/rpi-whoami
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - frontend

  web_server_5:
    image: hypriot/rpi-whoami
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - frontend

  web_server_6:
    image: hypriot/rpi-whoami
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - frontend

  load_balancer:
    image: hypriot/rpi-haproxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]
    depends_on:
      - web_server_1
      - web_server_2
      - web_server_3
      - web_server_4
      - web_server_5
      - web_server_6
    configs:
      - source: haproxy_config
        target: /haproxy-override/haproxy.cfg
        mode: 0744
    links:
      - web_server_1
      - web_server_2
      - web_server_3
      - web_server_4
      - web_server_5
      - web_server_6
    networks:
      - frontend
    ports:
      - "80:80"
      - "8080:8080"

configs:
  haproxy_config:
    external: true
      
networks:
  frontend:
    driver: overlay
