version: '3.2'

services:
  agent:
    image: hypriot/rpi-whoami
    ports:
      - target: 80
        published: 8001
        protocol: tcp
        mode: host
    networks:
      - scalable-web-frontend
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  scalable-web-frontend:
    driver: overlay
    attachable: true
